#g++ -std=c++17 LibModbusTestMaster.cpp -I ../../../../firmware/include/ModbusBasic/include -I /home/simon/Argus/ArgusMsdsProject/firmware/include/CppUtilities/include -lmodbus -I /usr/include/modbus/ -I ./
g++ -std=c++17 LibModbusTestMaster.cpp -I /usr/include/modbus/ -I ./ -lmodbus
